apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: ledger.transactions
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka-cluster
    domain: ledger
    type: event
spec:
  partitions: 24
  replicas: 3
  config:
    # Infinite retention for ledger (regulatory requirement)
    retention.ms: -1
    # Log compaction with tombstones
    cleanup.policy: compact
    delete.retention.ms: 31536000000  # 1 year tombstone retention
    min.compaction.lag.ms: 0
    # Maximum durability for financial ledger
    min.insync.replicas: 3
    # Uncompressed for audit integrity
    compression.type: none
    max.message.bytes: 2097152  # 2MB for transaction details
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: ledger.balances
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka-cluster
    domain: ledger
    type: state
spec:
  partitions: 24
  replicas: 3
  config:
    # Infinite retention
    retention.ms: -1
    # Compaction to keep latest balance
    cleanup.policy: compact
    min.compaction.lag.ms: 3600000  # 1 hour
    min.insync.replicas: 3
    compression.type: snappy
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: ledger.reconciliation
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka-cluster
    domain: ledger
    type: reconciliation
spec:
  partitions: 12
  replicas: 3
  config:
    # 1 year retention for reconciliation
    retention.ms: 31536000000
    cleanup.policy: delete
    min.insync.replicas: 2
    compression.type: snappy
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: ledger.snapshots
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka-cluster
    domain: ledger
    type: snapshot
spec:
  partitions: 12
  replicas: 3
  config:
    # 1 year retention for snapshots
    retention.ms: 31536000000
    cleanup.policy: compact
    min.insync.replicas: 2
    compression.type: lz4  # High compression for snapshots
