---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: audit.events
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka-cluster
    domain: audit
    type: audit
spec:
  partitions: 24
  replicas: 3
  config:
    # 7 years retention (regulatory requirement)
    retention.ms: 220898400000
    cleanup.policy: delete
    # High durability for audit trail
    min.insync.replicas: 3
    # No compression for audit integrity
    compression.type: none
    max.message.bytes: 2097152
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: audit.compliance
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka-cluster
    domain: audit
    type: compliance
spec:
  partitions: 12
  replicas: 3
  config:
    # 7 years retention
    retention.ms: 220898400000
    cleanup.policy: delete
    min.insync.replicas: 3
    compression.type: none
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: audit.security
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka-cluster
    domain: audit
    type: security
spec:
  partitions: 12
  replicas: 3
  config:
    # 7 years retention
    retention.ms: 220898400000
    cleanup.policy: delete
    min.insync.replicas: 3
    compression.type: none
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: audit.regulatory
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka-cluster
    domain: audit
    type: regulatory
spec:
  partitions: 12
  replicas: 3
  config:
    # 10 years retention (regulatory requirement)
    retention.ms: 315360000000
    cleanup.policy: delete
    min.insync.replicas: 3
    compression.type: none
