---
# ServiceAccount for Schema Registry
apiVersion: v1
kind: ServiceAccount
metadata:
  name: schema-registry
  namespace: kafka
  labels:
    app: schema-registry
---
# Role for Schema Registry - read access to config maps and secrets
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: schema-registry
  namespace: kafka
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
---
# RoleBinding to bind ServiceAccount to Role
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: schema-registry
  namespace: kafka
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: schema-registry
subjects:
  - kind: ServiceAccount
    name: schema-registry
    namespace: kafka
---
# PersistentVolumeClaim for Schema Registry data
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: schema-registry-data
  namespace: kafka
  labels:
    app: schema-registry
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi  # Schema metadata storage
  storageClassName: standard  # Adjust based on your cluster
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: schema-registry
  namespace: kafka
spec:
  replicas: 2
  selector:
    matchLabels:
      app: schema-registry
  template:
    metadata:
      labels:
        app: schema-registry
    spec:
      serviceAccountName: schema-registry  # Bind ServiceAccount
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: node-role.kubernetes.io/kafka
                    operator: In
                    values:
                      - "true"
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - schema-registry
                topologyKey: kubernetes.io/hostname
      containers:
        - name: schema-registry
          image: confluentinc/cp-schema-registry:7.5.0
          ports:
            - containerPort: 8081
              name: schema-registry
          env:
            - name: SCHEMA_REGISTRY_HOST_NAME
              value: schema-registry
            - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
              value: "fintech-kafka-kafka-bootstrap:9092"
            - name: SCHEMA_REGISTRY_LISTENERS
              value: "http://0.0.0.0:8081"
            - name: SCHEMA_REGISTRY_KAFKASTORE_TOPIC
              value: "_schemas"
            - name: SCHEMA_REGISTRY_KAFKASTORE_TOPIC_REPLICATION_FACTOR
              value: "3"
            # Data directory for local caching
            - name: SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL
              value: "fintech-kafka-zookeeper-client:2181"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
              ephemeral-storage: "1Gi"  # Local cache storage
            limits:
              memory: "1Gi"
              cpu: "500m"
              ephemeral-storage: "2Gi"
          volumeMounts:
            - name: data
              mountPath: /var/lib/schema-registry
            - name: tmp
              mountPath: /tmp
          livenessProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: 20
            periodSeconds: 5
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: schema-registry-data
        - name: tmp
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: schema-registry
  namespace: kafka
spec:
  selector:
    app: schema-registry
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
