---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: audit-service
  namespace: kafka
  labels:
    strimzi.io/cluster: fintech-kafka
    domain: audit
    service: audit-service
spec:
  # TLS client authentication
  authentication:
    type: tls

  # Authorization with ACLs
  authorization:
    type: simple
    acls:
      # ==========================================
      # PRODUCER PERMISSIONS - Audit Topics
      # ==========================================

      # Produce to audit events topic
      - resource:
          type: topic
          name: audit.events
        operations:
          - Write
          - Describe
        host: "*"

      # Produce to compliance events topic
      - resource:
          type: topic
          name: audit.compliance
        operations:
          - Write
          - Describe
        host: "*"

      # Produce to security events topic
      - resource:
          type: topic
          name: audit.security
        operations:
          - Write
          - Describe
        host: "*"

      # Produce to regulatory events topic
      - resource:
          type: topic
          name: audit.regulatory
        operations:
          - Write
          - Describe
        host: "*"

      # ==========================================
      # CONSUMER PERMISSIONS - Audit Topics
      # ==========================================

      # Consume from audit events (for aggregation)
      - resource:
          type: topic
          name: audit.events
        operations:
          - Read
          - Describe
        host: "*"

      # Consume from compliance events
      - resource:
          type: topic
          name: audit.compliance
        operations:
          - Read
          - Describe
        host: "*"

      # Consume from security events
      - resource:
          type: topic
          name: audit.security
        operations:
          - Read
          - Describe
        host: "*"

      # Consume from regulatory events
      - resource:
          type: topic
          name: audit.regulatory
        operations:
          - Read
          - Describe
        host: "*"

      # Consumer group for audit service
      - resource:
          type: group
          name: audit-service
        operations:
          - Read
        host: "*"

      # Consumer group for compliance reporter
      - resource:
          type: group
          name: audit-service-compliance-reporter
        operations:
          - Read
        host: "*"

      # Consumer group for security monitor
      - resource:
          type: group
          name: audit-service-security-monitor
        operations:
          - Read
        host: "*"

      # Consumer group for regulatory exporter
      - resource:
          type: group
          name: audit-service-regulatory-exporter
        operations:
          - Read
        host: "*"

      # ==========================================
      # CROSS-DOMAIN PERMISSIONS (Read-Only Monitoring)
      # ==========================================

      # Consume from ALL payments topics (audit trail)
      - resource:
          type: topic
          name: payments.commands
        operations:
          - Read
          - Describe
        host: "*"

      - resource:
          type: topic
          name: payments.events
        operations:
          - Read
          - Describe
        host: "*"

      - resource:
          type: topic
          name: payments.validations
        operations:
          - Read
          - Describe
        host: "*"

      - resource:
          type: topic
          name: payments.dead-letter
        operations:
          - Read
          - Describe
        host: "*"

      # Consume from ALL ledger topics (financial audit)
      - resource:
          type: topic
          name: ledger.transactions
        operations:
          - Read
          - Describe
        host: "*"

      - resource:
          type: topic
          name: ledger.balances
        operations:
          - Read
          - Describe
        host: "*"

      - resource:
          type: topic
          name: ledger.reconciliation
        operations:
          - Read
          - Describe
        host: "*"

      # Consume from ALL notification topics (delivery tracking)
      - resource:
          type: topic
          name: notifications.email
        operations:
          - Read
          - Describe
        host: "*"

      - resource:
          type: topic
          name: notifications.sms
        operations:
          - Read
          - Describe
        host: "*"

      - resource:
          type: topic
          name: notifications.push
        operations:
          - Read
          - Describe
        host: "*"

      - resource:
          type: topic
          name: notifications.audit
        operations:
          - Read
          - Describe
        host: "*"

      # Consumer groups for cross-domain monitoring
      - resource:
          type: group
          name: audit-service-payments-monitor
        operations:
          - Read
        host: "*"

      - resource:
          type: group
          name: audit-service-ledger-monitor
        operations:
          - Read
        host: "*"

      - resource:
          type: group
          name: audit-service-notifications-monitor
        operations:
          - Read
        host: "*"

      # ==========================================
      # TRANSACTIONAL PERMISSIONS
      # ==========================================

      # Transactional ID for audit integrity
      - resource:
          type: transactionalId
          name: audit-service
          patternType: prefix
        operations:
          - Describe
          - Write
        host: "*"

  # Resource quotas (highest for audit - must capture everything)
  quotas:
    producerByteRate: 20971520  # 20 MB/s
    consumerByteRate: 31457280  # 30 MB/s (consumes from all domains)
    requestPercentage: 70       # 70% of broker CPU time
    controllerMutationRate: 10  # 10 mutations/sec

---
# ConfigMap for client configuration template
apiVersion: v1
kind: ConfigMap
metadata:
  name: audit-service-kafka-config
  namespace: kafka
data:
  application.properties: |
    # Kafka Bootstrap Servers
    bootstrap.servers=fintech-kafka-kafka-bootstrap:9093

    # Security Configuration
    security.protocol=SSL
    ssl.truststore.location=/etc/kafka-certs/ca.p12
    ssl.truststore.password=${TRUSTSTORE_PASSWORD}
    ssl.keystore.location=/etc/kafka-certs/user.p12
    ssl.keystore.password=${KEYSTORE_PASSWORD}

    # Producer Configuration
    key.serializer=org.apache.kafka.common.serialization.StringSerializer
    value.serializer=io.confluent.kafka.serializers.KafkaAvroSerializer
    schema.registry.url=http://schema-registry:8081

    # Exactly-once semantics - CRITICAL for audit integrity
    enable.idempotence=true
    acks=all
    max.in.flight.requests.per.connection=5
    transactional.id=audit-service-${POD_NAME}

    # Performance tuning
    batch.size=32768
    linger.ms=50  # Balance between latency and throughput
    compression.type=none  # No compression for tamper-proof audit trail
    buffer.memory=67108864

    # Consumer Configuration
    key.deserializer=org.apache.kafka.common.serialization.StringDeserializer
    value.deserializer=io.confluent.kafka.serializers.KafkaAvroDeserializer

    # Consumer group
    group.id=audit-service

    # Exactly-once for consumers
    enable.auto.commit=false
    isolation.level=read_committed

    # Consumer tuning (must not miss any events)
    fetch.min.bytes=1
    fetch.max.wait.ms=100  # Low latency for real-time audit
    max.poll.records=500
    max.poll.interval.ms=300000

    # CRITICAL: Never skip events
    auto.offset.reset=earliest

    # Reliability
    retries=Integer.MAX_VALUE
    retry.backoff.ms=1000

    # Monitoring
    metrics.recording.level=DEBUG

    # Compliance Configuration
    # Note: Audit service should store ALL events for regulatory period
    # Retention handled at topic level (7-10 years)
