---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: payments-service
  namespace: kafka
  labels:
    strimzi.io/cluster: fintech-kafka
    domain: payments
    service: payments-service
spec:
  # TLS client authentication
  authentication:
    type: tls

  # Authorization with ACLs
  authorization:
    type: simple
    acls:
      # ==========================================
      # PRODUCER PERMISSIONS - Payments Topics
      # ==========================================

      # Produce to payments commands topic
      - resource:
          type: topic
          name: payments.commands
        operations:
          - Write
          - Describe
        host: "*"

      # Produce to payments events topic
      - resource:
          type: topic
          name: payments.events
        operations:
          - Write
          - Describe
        host: "*"

      # Produce to payments validations topic
      - resource:
          type: topic
          name: payments.validations
        operations:
          - Write
          - Describe
        host: "*"

      # Produce to payments dead-letter topic
      - resource:
          type: topic
          name: payments.dead-letter
        operations:
          - Write
          - Describe
        host: "*"

      # ==========================================
      # CONSUMER PERMISSIONS - Payments Topics
      # ==========================================

      # Consume from payments commands topic
      - resource:
          type: topic
          name: payments.commands
        operations:
          - Read
          - Describe
        host: "*"

      # Consume from payments events topic (for saga compensation)
      - resource:
          type: topic
          name: payments.events
        operations:
          - Read
          - Describe
        host: "*"

      # Consumer group for payments service
      - resource:
          type: group
          name: payments-service
        operations:
          - Read
        host: "*"

      # Consumer group for payment processors (scaling)
      - resource:
          type: group
          name: payments-service-processor
        operations:
          - Read
        host: "*"

      # ==========================================
      # CROSS-DOMAIN PERMISSIONS
      # ==========================================

      # Produce to audit events (for compliance)
      - resource:
          type: topic
          name: audit.events
        operations:
          - Write
          - Describe
        host: "*"

      # ==========================================
      # TRANSACTIONAL PERMISSIONS (for exactly-once)
      # ==========================================

      # Transactional ID for exactly-once semantics
      - resource:
          type: transactionalId
          name: payments-service
          patternType: prefix
        operations:
          - Describe
          - Write
        host: "*"

  # ==========================================
  # SCHEMA REGISTRY INTEGRATION
  # ==========================================

  # Note: Schema Registry uses separate auth
  # These ACLs are for Kafka-only permissions

  # Resource quotas
  quotas:
    producerByteRate: 10485760  # 10 MB/s
    consumerByteRate: 10485760  # 10 MB/s
    requestPercentage: 50       # 50% of broker CPU time
    controllerMutationRate: 10  # 10 mutations/sec

---
# ConfigMap for client configuration template
apiVersion: v1
kind: ConfigMap
metadata:
  name: payments-service-kafka-config
  namespace: kafka
data:
  application.properties: |
    # Kafka Bootstrap Servers
    bootstrap.servers=fintech-kafka-kafka-bootstrap:9093

    # Security Configuration
    security.protocol=SSL
    ssl.truststore.location=/etc/kafka-certs/ca.p12
    ssl.truststore.password=${TRUSTSTORE_PASSWORD}
    ssl.keystore.location=/etc/kafka-certs/user.p12
    ssl.keystore.password=${KEYSTORE_PASSWORD}

    # Producer Configuration
    key.serializer=org.apache.kafka.common.serialization.StringSerializer
    value.serializer=io.confluent.kafka.serializers.KafkaAvroSerializer
    schema.registry.url=http://schema-registry:8081

    # Exactly-once semantics (Phase B)
    enable.idempotence=true
    acks=all
    max.in.flight.requests.per.connection=5
    transactional.id=payments-service-${POD_NAME}

    # Performance tuning
    batch.size=16384
    linger.ms=10
    compression.type=snappy
    buffer.memory=33554432

    # Consumer Configuration
    key.deserializer=org.apache.kafka.common.serialization.StringDeserializer
    value.deserializer=io.confluent.kafka.serializers.KafkaAvroDeserializer

    # Consumer group
    group.id=payments-service

    # Exactly-once for consumers
    enable.auto.commit=false
    isolation.level=read_committed

    # Consumer tuning
    fetch.min.bytes=1
    fetch.max.wait.ms=500
    max.poll.records=500
    max.poll.interval.ms=300000

    # Monitoring
    metrics.recording.level=DEBUG
