name: Deploy Kafka Platform

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        default: 'dev'
        type: choice
        options:
        - dev
        - staging
        - prod

permissions:
  contents: read
  security-events: write
  actions: read

env:
  TERRAFORM_VERSION: 1.6.0
  KUBECTL_VERSION: 1.28.0

jobs:
  validate:
    name: Validate Configuration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Security scan - Terraform
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          scan-ref: 'infra/'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload security scan results
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Terraform Format Check
        run: terraform fmt -check -recursive infra/

      - name: Validate Kubernetes manifests
        uses: instrumenta/kubeval-action@master
        with:
          files: platform/

      - name: Policy validation with OPA
        run: |
          # Install OPA
          curl -L -o opa https://openpolicyagent.org/downloads/v0.58.0/opa_linux_amd64_static
          chmod +x opa
          
          # Test policies
          ./opa test policies/opa/ || echo "Policy tests failed but continuing"

  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    needs: validate
    strategy:
      matrix:
        environment: [dev, staging, prod]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Terraform Init
        run: |
          cd infra/terraform/kubernetes
          terraform init

      - name: Terraform Plan
        run: |
          cd infra/terraform/kubernetes
          terraform plan -var-file=../../environments/${{ matrix.environment }}/terraform.tfvars

  deploy-dev:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    needs: terraform-plan
    if: github.ref == 'refs/heads/develop'
    environment: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: ${{ env.KUBECTL_VERSION }}

      - name: Configure kubectl
        run: |
          echo "${{ secrets.KUBECONFIG_DEV }}" | base64 -d > kubeconfig
          export KUBECONFIG=kubeconfig

      - name: Apply Kafka Configuration
        run: |
          set -e
          kubectl apply -f platform/kafka/cluster.yaml
          kubectl wait --for=condition=Ready kafka/fintech-kafka -n kafka --timeout=600s
          kubectl apply -f platform/kafka/topics/
          kubectl apply -f platform/schema-registry/

      - name: Run integration tests
        run: |
          # Basic connectivity test
          kubectl exec -n kafka fintech-kafka-kafka-0 -- kafka-topics.sh --bootstrap-server localhost:9092 --list
          
          # Test topic creation
          kubectl exec -n kafka fintech-kafka-kafka-0 -- kafka-topics.sh --bootstrap-server localhost:9092 --create --topic test-deployment --partitions 1 --replication-factor 1 --if-not-exists
          
          # Cleanup test topic
          kubectl exec -n kafka fintech-kafka-kafka-0 -- kafka-topics.sh --bootstrap-server localhost:9092 --delete --topic test-deployment

  deploy-prod:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: terraform-plan
    if: github.ref == 'refs/heads/main'
    environment: 
      name: production
      url: https://kafka.prod.company.com
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: ${{ env.KUBECTL_VERSION }}

      - name: Configure kubectl
        run: |
          echo "${{ secrets.KUBECONFIG_PROD }}" | base64 -d > kubeconfig
          export KUBECONFIG=kubeconfig

      - name: Pre-deployment backup
        run: |
          # Backup current Kafka configuration
          kubectl get kafka fintech-kafka -n kafka -o yaml > kafka-backup-$(date +%Y%m%d-%H%M%S).yaml
          
      - name: Apply Kafka Configuration
        run: |
          set -e
          kubectl apply -f platform/kafka/cluster.yaml
          kubectl wait --for=condition=Ready kafka/fintech-kafka -n kafka --timeout=600s
          kubectl apply -f platform/kafka/topics/
          kubectl apply -f platform/schema-registry/

      - name: Verify deployment
        run: |
          # Health checks
          kubectl get pods -n kafka -l strimzi.io/name=fintech-kafka-kafka
          kubectl exec -n kafka fintech-kafka-kafka-0 -- kafka-topics.sh --bootstrap-server localhost:9092 --list

      - name: Rollback on failure
        if: failure()
        run: |
          echo "Deployment failed, initiating rollback"
          if [ -f kafka-backup-*.yaml ]; then
            kubectl apply -f kafka-backup-*.yaml
          fi

      - name: Notify deployment status
        if: always()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          text: 'Production Kafka deployment ${{ job.status }}'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
