name: Deploy Kafka Platform

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

env:
  TERRAFORM_VERSION: 1.6.0
  KUBECTL_VERSION: 1.28.0

jobs:
  validate:
    name: Validate Configuration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Terraform Format Check
        run: terraform fmt -check -recursive infra/

      - name: Validate Kubernetes manifests
        uses: instrumenta/kubeval-action@master
        with:
          files: platform/

  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    needs: validate
    strategy:
      matrix:
        environment: [dev, staging, prod]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Terraform Init
        run: |
          cd infra/terraform/kubernetes
          terraform init

      - name: Terraform Plan
        run: |
          cd infra/terraform/kubernetes
          terraform plan -var-file=../../environments/${{ matrix.environment }}/terraform.tfvars

  deploy-dev:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    needs: terraform-plan
    if: github.ref == 'refs/heads/develop'
    environment: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: ${{ env.KUBECTL_VERSION }}

      - name: Configure kubectl
        run: |
          echo "${{ secrets.KUBECONFIG_DEV }}" | base64 -d > kubeconfig
          export KUBECONFIG=kubeconfig

      - name: Apply Kafka Configuration
        run: |
          kubectl apply -f platform/kafka/cluster.yaml
          kubectl apply -f platform/kafka/topics/
          kubectl apply -f platform/schema-registry/

  deploy-prod:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: terraform-plan
    if: github.ref == 'refs/heads/main'
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: ${{ env.KUBECTL_VERSION }}

      - name: Configure kubectl
        run: |
          echo "${{ secrets.KUBECONFIG_PROD }}" | base64 -d > kubeconfig
          export KUBECONFIG=kubeconfig

      - name: Apply Kafka Configuration
        run: |
          kubectl apply -f platform/kafka/cluster.yaml
          kubectl apply -f platform/kafka/topics/
          kubectl apply -f platform/schema-registry/
